### ISSUE TITLE
server gives error on Win10 x64

### ISSUE THREAD

**Issue by Alexey-T** [bitbegin/redlangserver#7]
- c:\red\red.exe - version from 30-sept-2021,
- c:\red\redlangserver - folder of repo
- c:\red\redlangserver.cmd - file:
```
c:\red\red.exe c:\red\redlangserver\server.red
```

- added c:\Red to PATH.

Now i run Win Console (cmd.exe) and do `redlangserver`, it shows GUI console with errors:
```
*** Script Error: path json-body/id: is not valid for none! type
*** Where: set-path
*** Stack: 
>> 
```

@loziniak @hiiamboris

**Comment by hiiamboris** [comment]
`red.exe --cli server.red`
as we discovered the server relies on some temporary stdin/stdout functions provided only by CLI console
